# Generated by Django 6.0.1 on 2026-01-10 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='worker_photos/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='dob',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone',
            field=models.CharField(default=datetime.date(2000, 1, 1), max_length=15),
            preserve_default=False,
        ),
    ]
