# Generated by Django 6.0.1 on 2026-01-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_worker_email_worker_photo_alter_userprofile_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
